name: hello-node-snap-image
version: "1.0.2"
summary: A simple hello world command
description: A command that simply prints hello world 
confinement: strict

apps:
  hello-node-snap:
    command: bin/hello-node-snap
    plugs: [network]

parts:
  hello-node-snap:
    plugin: nodejs
    node-packages:
      - hello-node-snap
